name: Test docker before merge
on:
  pull_request:
      branches: [ main ]
jobs:
  build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          
          - name: Build Docker Image
            run: docker build --tag unitconv .
          
          - name: Run Docker
            run: docker run -d --name container -p 80:3000 unitconv
            
          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: '3.9'
              
          - name: Install the necessary packages
            run: pip install requests webdriver-manager selenium pytest
            
          - name: Run the PytTest script
            run: pytest -rA
